### ISSUE TITLE
Allow Repositories to be Configured in `settings.json`

### ISSUE THREAD

**Issue by manuth** [zokugun/vscode-sync-settings#16]
Especially when working with remote endpoints (such as git repositories, SSH, SCP, SFTP etc.) it might be very useful to be able to configure common variables (the hostname, port, username etc.) in `settings.json` which would make using `vscode-sync-settings` easier alongside VSCodes built-in settings-sync

**Comment by daiyam** [comment]
Hi, I'm not quite sure to understand what you want.
By doing some remote dev, vscode has local and remote extensions. The local extensions can be sync with this extension or the builtin feature. Remote extensions are manage with the settings `remote.SSH.defaultExtensions`.
Can you explain a bit more so I understand your usage? Thx

**Comment by manuth** [comment]
Hi @daiyam
Sorry for the confusion, I think I was a little too unclear.
I thought it might be a good idea to have the ability to store settings (such as `hostname`, `port`, `username` etc.) in the `settings.json` in order to be able to sync these settings through Microsoft's built-in settings synchronization.

That way one could initially enable Microsoft's built-in sync in order to fetch the `vscode-settings-sync` repository options and use `vscode-settings-sync` out of the box without further configuration.

But thinking through it I think what might sound great might cause some issues in reality (maybe?) because in order to have said settings being synced between VSCode installations, Microsoft's built-in settings synchronization would have to be enabled and this, then again, might conflict with the `vscode-sync-settings` extension.

**Comment by daiyam** [comment]
To be honest, I haven't tried the builtin sync since I don't use the official version of vscode. I'm using my fork mainly to better support explicit foldings... So I don't know if there is any conflict...
I could see a way for what you want (create a basic builtin sync, logout, then only sync with the extension) but it's cumbersome... Why not simply use the builtin feature?
And I'm a bit worried about username/password (webdav, ...) being sync with the builtin feature or by mistake to a public repo.
