### ISSUE TITLE
Commit messages including hostname

### ISSUE THREAD

**Issue by chmac** [zokugun/vscode-sync-settings#8]
I see the commit messages include timestamps and profile names, it would be awesome to also include the hostname, otherwise it's hard to know where that commit happened. I'd favour the hostname over the timestamp also, as the timestamp is part of the commit itself as well.

**Comment by daiyam** [comment]
I could add it as an option since some people wouldn't like that

**Comment by chmac** [comment]
@daiyam Yeah, this came up on dendron, which is another extension. Perhaps there's privacy implications. I'd say the chances are smaller here, it's unlikely I share my settings with somebody else and I'm passionate about keeping my hostname private, but it's definitely possible.

I suggested for dendron that they could have a setting, and if the setting is empty, the system hostname gets used. That way it's easy to customise but in general everybody gets the most helpful behaviour (knowing which machine added which settings).

**Comment by daiyam** [comment]
I will add the options to customize the commit messages.
By default it will be like: `profile({{profile}}): update -- {{now|date:iso}}`.
But you will be able to use `profile({{profile}}): update -- {{hostname}}`.

**Comment by chmac** [comment]
Awesome. Will that be a new setting in the next update?

**Comment by daiyam** [comment]
The new version is available. Tell me if you have any issues.

**Comment by daiyam** [comment]
I will need to move the git message into the VSCode's own settings so you can share them.
In VSCode' settings, I could a new property to generate the `hostname` based on the system's hostname or username.

`settings.yml` would never be synced because the extension will always need the infos inside that file to do any sync...

**Comment by daiyam** [comment]
> My hope would be that without `hostname` being set, the value will default to the system hostname. Would you be open to a PR that adds that behaviour?

In the new `v0.8.1`, you can do that by removing the `hostname` property in `settings.yml` and adding the `syncSettings.hostname` setting (in VSCode' settings) with the value `{{hostname}}`.

> I will need to move the git message into the VSCode's own settings so you can share them.

I've added the settings `syncSettings.gitInitMessage` and `syncSettings.gitUpdateMessage` so that you share the messages between your computers. (overwritten by the config in `settings.yml`)

**Comment by chmac** [comment]
That's awesome! 🥳 

I guess it'll only make sense to put `hostname` into the `settings.yml` file as the other settings are probably being synced. Is that right? I was trying to wrap my head around this. Having the commit messages in the VSCode settings is awesome, then I can just set them once and they will sync across my machines.

**Comment by chmac** [comment]
Just tested this out, and it works great for me. I removed the commit messages from `settings.yml` and left the hostname in there. Kinda makes sense in a way that the hostname needs to be on disk and not synced.

Thanks a lot for being so receptive to these requests and turning them around so fast.

**Comment by daiyam** [comment]
With `"syncSettings.hostname": "{{hostname}}"`, it will us the real host name of the system.
